### ISSUE TITLE
Add AddressSanitzer to regression tests

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#251]
It's so easy to use AddressSanitizer, I'm not sure why I don't use it by default. If I did, I would have caught this error earlier:
```
e) simsong@nimi src % ./bulk_extractor -1 -o out-foo2 ./bulk_extractor                                                                                           (slg-dev)bulk_extractor
bulk_extractor version: 2.0.0-dev
Input file: "./bulk_extractor"
Output directory: "out-foo2"
Disk Size: 20362224
Scanners: aes base64 elf evtx exif facebook find gzip hiberfile httplogs json kml msxml net ntfsindx ntfslogfile ntfsmft ntfsusn pdf rar sqlite utmp vcard windirs winlnk winpe winprefetch zip accts email gps
Threads: 6
cfg.opt_notificaiton=1  cfg=0x7ffeeb55ec00
going multi-threaded...(6)
22:14:08 Offset 0MB (0.00%) Done in n/a at
Calling check_previously_processed at one
All data are read; waiting for threads to finish...
22:14:09 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:10 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:11 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:12 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:13 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:14 Offset 16MB (100.00%) Done in  0:00:00 at
std::exception Scanner: kml Exception: filesystem error: in create_directory: No such file or directory [<NO-OUTDIR>/kml] sbuf.pos0: (|0) bufsize=20362224
22:14:15 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:16 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:17 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:18 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:19 Offset 16MB (100.00%) Done in  0:00:00 at
22:14:20 Offset 16MB (100.00%) Done in  0:00:00 at
AddressSanitizer:DEADLYSIGNAL
=================================================================
==38027==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000068 (pc 0x7fff2031625c bp 0x70000705ab30 sp 0x70000705ab20 T6)
==38027==The signal is caused by a READ memory access.
==38027==Hint: address points to the zero page.
    #0 0x7fff2031625c in flockfile+0x12 (libsystem_c.dylib:x86_64+0x3925c)
    #1 0x7fff203194d0 in fwrite+0x41 (libsystem_c.dylib:x86_64+0x3c4d0)
    #2 0x105fb5ae2 in wrap_fwrite+0x52 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1eae2)
    #3 0x104b0a61d in pcap_writer::pcap_write4(unsigned int) const scan_net.h:217
    #4 0x104b09ce2 in pcap_writer::pcap_writepkt(scan_net_t::pcap_hdr const&, sbuf_t const&, unsigned long, bool, unsigned short) const scan_net.cpp:780
    #5 0x104b0b28e in scan_net_t::carvePCAPPacket(sbuf_t const&, unsigned long) const scan_net.cpp:859
    #6 0x104b0c5c5 in scan_net_t::carve(sbuf_t const&) const scan_net.cpp:917
    #7 0x104b0e1fd in scan_net scan_net.cpp:982
    #8 0x10483e948 in scanner_set::process_sbuf(sbuf_t*) scanner_set.cpp:771
    #9 0x10489fb68 in scanner_set::schedule_sbuf(sbuf_t*)::$_0::operator()() const scanner_set.cpp:840
    #10 0x10489fabc in decltype(std::__1::forward<scanner_set::schedule_sbuf(sbuf_t*)::$_0&>(fp)()) std::__1::__invoke<scanner_set::schedule_sbuf(sbuf_t*)::$_0&>(scanner_set::schedule_sbuf(sbuf_t*)::$_0&) type_traits:3747
    #11 0x10489fa6c in void std::__1::__invoke_void_return_wrapper<void>::__call<scanner_set::schedule_sbuf(sbuf_t*)::$_0&>(scanner_set::schedule_sbuf(sbuf_t*)::$_0&) __functional_base:348
    #12 0x10489fa3c in std::__1::__function::__alloc_func<scanner_set::schedule_sbuf(sbuf_t*)::$_0, std::__1::allocator<scanner_set::schedule_sbuf(sbuf_t*)::$_0>, void ()>::operator()() functional:1553
    #13 0x10489c21d in std::__1::__function::__func<scanner_set::schedule_sbuf(sbuf_t*)::$_0, std::__1::allocator<scanner_set::schedule_sbuf(sbuf_t*)::$_0>, void ()>::operator()() functional:1727
    #14 0x10484fa95 in std::__1::__function::__value_func<void ()>::operator()() const functional:1880
    #15 0x10484e304 in std::__1::function<void ()>::operator()() const functional:2555
    #16 0x10484dcf5 in thread_pool::worker() thread_pool.hpp:348
    #17 0x104854bcf in decltype(*(std::__1::forward<thread_pool*>(fp0)).*fp()) std::__1::__invoke<void (thread_pool::*)(), thread_pool*, void>(void (thread_pool::*&&)(), thread_pool*&&) type_traits:3688
    #18 0x104854a3d in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (thread_pool::*)(), thread_pool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (thread_pool::*)(), thread_pool*>&, std::__1::__tuple_indices<2ul>) thread:280
    #19 0x1048538fe in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (thread_pool::*)(), thread_pool*> >(void*) thread:291
    #20 0x7fff204088fb in _pthread_start+0xdf (libsystem_pthread.dylib:x86_64+0x68fb)
    #21 0x7fff20404442 in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x2442)

==38027==Register values:
rax = 0x000070000705e0ac  rbx = 0x0000000000000000  rcx = 0x000070000705e0ac  rdx = 0x0000000000000004
rdi = 0x0000000000000000  rsi = 0x0000000000000001  rbp = 0x000070000705ab30  rsp = 0x000070000705ab20
 r8 = 0x0000100000000000   r9 = 0xffffffff00000000  r10 = 0x00007fff80700450  r11 = 0x0000000000000207
r12 = 0x0000000000000004  r13 = 0x0000000000000000  r14 = 0x0000000000000002  r15 = 0x0000000000000001
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_c.dylib:x86_64+0x3925c) in flockfile+0x12
Thread T6 created by T0 here:
    #0 0x105fd958a in wrap_pthread_create+0x5a (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4258a)
    #1 0x1048537b3 in std::__1::__libcpp_thread_create(_opaque_pthread_t**, void* (*)(void*), void*) __threading_support:501
    #2 0x1048533b7 in std::__1::thread::thread<void (thread_pool::*)(), thread_pool*, void>(void (thread_pool::*&&)(), thread_pool*&&) thread:307
    #3 0x10484de74 in std::__1::thread::thread<void (thread_pool::*)(), thread_pool*, void>(void (thread_pool::*&&)(), thread_pool*&&) thread:299
    #4 0x10484c6a7 in thread_pool::create_threads() thread_pool.hpp:292
    #5 0x10484c36f in thread_pool::thread_pool(unsigned int const&) thread_pool.hpp:51
    #6 0x10482b93c in thread_pool::thread_pool(unsigned int const&) thread_pool.hpp:50
    #7 0x10482b7c2 in scanner_set::launch_workers(int) scanner_set.cpp:119
    #8 0x104905875 in bulk_extractor_main(int, char* const*) bulk_extractor.cpp:717
    #9 0x104cf7f21 in main main.cpp:13
    #10 0x7fff20423f3c in start+0x0 (libdyld.dylib:x86_64+0x15f3c)

==38027==ABORTING
zsh: abort      ./bulk_extractor -1 -o out-foo2 ./bulk_extractor
(base)
```

I also need to add a self-test where bulk_extractor is just run on a file or something (here it is run on itself).

**Comment by simsong** [comment]
It's in the unit tests now!
